<?php
defined('MOODLE_INTERNAL') || die();

$functions = [

    'mod_slideshow_view_slide' => [
        'classname'   => 'mod_slideshow\external',
        'methodname'  => 'view_slide',
        'description' => 'Records the highest slide number a user has viewed and handles completion.',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'mod/slideshow:view',
    ],
    'mod_slideshow_reorder' => [
        'classname'   => 'mod_slideshow\external\reorder',
        'methodname'  => 'execute',
        'classpath'   => '',
        'description' => 'Reorder slideshow images and extra slides by key (pathnamehash, filename, or extra_NNN)',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'mod/slideshow:manage',
    ],
    'mod_slideshow_generate_voiceover' => [
        'classname'   => 'mod_slideshow\external\generate_voiceover',
        'methodname'  => 'execute',
        'classpath'   => '',
        'description' => 'Generate AI voiceover for a single slide image using OCR + Chirp 3 HD TTS',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'mod/slideshow:manage',
    ],
    'mod_slideshow_generate_all_voiceovers' => [
        'classname'   => 'mod_slideshow\external\generate_all_voiceovers',
        'methodname'  => 'execute',
        'classpath'   => '',
        'description' => 'Generate AI voiceovers for all slides in a slideshow',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'mod/slideshow:manage',
    ],
    'mod_slideshow_save_slide_text' => [
        'classname'   => 'mod_slideshow\external\save_slide_text',
        'methodname'  => 'execute',
        'classpath'   => '',
        'description' => 'Save custom voiceover text for a single slide',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'mod/slideshow:manage',
    ],
    'mod_slideshow_upload_draft_file' => [
        'classname'   => 'mod_slideshow\external\upload_draft_file',
        'methodname'  => 'execute',
        'classpath'   => '',
        'description' => 'Upload a file directly to user draft area (bypasses repository system)',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'mod/slideshow:manage',
    ],
    'mod_slideshow_toggle_voiceover_disabled' => [
        'classname'   => 'mod_slideshow\external\toggle_voiceover_disabled',
        'methodname'  => 'execute',
        'classpath'   => '',
        'description' => 'Enable or disable voiceover for a single slide (skips generation and hides playback controls)',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'mod/slideshow:manage',
    ],
    'mod_slideshow_save_extra_slide' => [
        'classname'   => 'mod_slideshow\external\save_extra_slide',
        'methodname'  => 'execute',
        'classpath'   => '',
        'description' => 'Create or update a video or poster extra slide and insert at the chosen position',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'mod/slideshow:manage',
    ],
    'mod_slideshow_delete_extra_slide' => [
        'classname'   => 'mod_slideshow\external\delete_extra_slide',
        'methodname'  => 'execute',
        'classpath'   => '',
        'description' => 'Delete a video or poster extra slide and compact sortorders',
        'type'        => 'write',
        'ajax'        => true,
        'capabilities'=> 'mod/slideshow:manage',
    ],
];
